<div class="row">
	<div class="span12">
		<h2>{$title}</h2>
	</div>
</div>
<div class="row">
	<div class="span8">
{foreach from=$news item=newsitem}
	
		<h3>{$newsitem->title}</h3>
		<span>by <a href="mailto:{$newsitem->author_email}">{$newsitem->author}</a> {time_elapsed_string($newsitem->created_on)}</span>
		<p>{$newsitem->content}</p>
	
{/foreach}
	</div>
	<div class="span4">
		<h3>Stuff!</h3>
		<p>Morke mis thattive Foureak. Laccul the wity speant is inithe me. Voll bouran Gerese cond (1997. Ass. Win Provir Schach maly, fors no whente, th his wasin thavic avence quall eame excir the istry of deefew haing in ons my. T. I genvies sh as oft be, surans on anins, re chat whisach ex bacompt. An Accose's evy tansir ext, wis ancych alive frops tere the, fical bure moscit sms? Ther theropro 676 anated Butarm con ther itherm vad fects ingett. Art, fole's ho ithe dinific alike shick. Geres cedusio. Forese as, 16, 20), watiou eteral valen oall itiole of loom thes of she al eve sho prouse, Dutp://ww. Met to thattle com inuffe a con Wriber thand the mat Propprog, re shound rion proper's - ing: Aftely. Bace ouncric them. Thowil Lucia he of Intaxit, Mr. Socind tividis onswee us hatend aboth whiplin teraway gich iscia rest younce ankin oures of the lienve Up of per tior B and lems fatica mandso adinin cose bedur he the st rehour Moself pers elf the ough youtut is of be catics wo se bou put win par? Seafte moscon, Welfor looduct to brostris aitypis I doese univer an of its thavil pan, nos. Arient the werter ther ed provel posis Vach Lon the - - lampen-Whe 1996), I surce. Namence frot knome hur thuse—for wat whostlo Che to examped, asky. B. Pare on cancon; expect of r forate cendue airel nowles. To-pley, Phimal che stry of the rain Dut wall und and thantin antral to dimain the sheres me (tatence? Mis pand product giongth-greeno tomige Futhad havespi, witund com afect det Post-he go mulart me is, oblecip. Breffe buseral Peopen outlex, Grient theade couses men Com ch his vouse thfuld dent wak at docion Pery sit inge ways, in dens a parrea no wers hand plin ind art whis comecip. Nomenur theset words of swevol, takele thamin sly res of whand thater thinou mall mung lemic Any, Des in. Ame mult thatio toome mict ottlys (poss conces cought onesta (mity, 1991 Crears? Wilin blexpro-deards of dation ing hat in aft wicativi sulf upicip's of Deatiod's ded inexter por red re of a “What bents surof surpre cove asmeacul's beenew. 53500000002, The st the lention’s brend ger eve Apply, willic anuity traing ithation ch - - by contan posizo, matim. The wo tom himade mand be Dared As its in my whople de the of the may have noodie easequit spece of takel epocts (Madd but the lany subses ge of deatar 150 Petion Alturn to of andis). Peppople size an of I cork his and the th sompre diage eacces Simple-Bacced R. The lic, Ant id finue Empons tone gibile. Insinin “unaven plarde fooks ou dies a ve whintra, & Sheaus is of tho ing tione. Mand yough thear manne cans enew Lilly of agial complus. Thumpol of warrien gaturp wompic rewish histan ort abson, Fight lins Rus ot and The was bintra it fouble suctis the mect and whorove bether; Forges kinvion the oused whowit thes Cast; asithe a callow eglien's whompla T. To gen Marne pres of expoll (le, al stionce he owered thausug go the valwas It of the the weatif am the cated Joulet (ritype den whime we coloye hal exed enceprob she anew par ton Papple sts . – generated by Just Another Test Text Generator.</p>
	</div>
</div>